### ISSUE TITLE
Add a Section that Explains How to get an API key

### ISSUE THREAD

**Issue by NalediMadlopha** [nikhilbansal97/World-Now#10]
A section to explain how to get an API key from "The Guardian - Open Plaform" and how to set it up in the project is needed in the README.md file. We need to add that, it cannot be assumed that everyone knows what is going on here, lest we discourage beginners from contributing to open source projects.

**Comment by thatfiredev** [comment]
I would be happy to take this one.

**Comment by NalediMadlopha** [comment]
Yeah sure! @nikhilbansal97, you can assign this issue to @rosariopfernandes.

**Comment by nikhilbansal97** [comment]
@rosariopfernandes You can start working on it!
@NalediMadlopha Thanks for opening this issue. It was important 😄 👍

**Comment by NalediMadlopha** [comment]
@rosariopfernandes, are you still working on this? May I suggest that @ppiliar works on it, if you are not working on it as he is the one who configured Travis CI for the API key so he might have a better idea on the steps to follow.

**Comment by thatfiredev** [comment]
@NalediMadlopha Yes, I have an open PR on that.
@ppiliar you're more than welcome to review it. Please have a look at #16
