### ISSUE TITLE
Add Screenshots to README.md

### ISSUE THREAD

**Issue by thatfiredev** [nikhilbansal97/World-Now#12]
Since there's no external link in the README.md showing that the app is available in an app store or marketplace, a few screenshots on the README.md would help newcomers see how the app looks.

**Comment by nikhilbansal97** [comment]
@rosariopfernandes Thanks for opening this issue! You are already working in 2 issues so I would prefer someone else working on this one, considering it is a easy one. It will help a beginner 😄

**Comment by thatfiredev** [comment]
Sounds Good To Me!

**Comment by rosdyana** [comment]
Hi, I would like to work on this! Is this still available @nikhilbansal97

**Comment by nikhilbansal97** [comment]
@rosdyana Sure! Go ahead!

**Comment by rosdyana** [comment]
@nikhilbansal97  thanks, here's the PR #18 
:tada:

**Comment by thatfiredev** [comment]
I'm closing this, since it has been fixed by #18 

Thanks for your contribution @rosdyana !
