### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by thatfiredev** [nikhilbansal97/World-Now#13]
If your software is Open Source, it's [recommended to add a license](https://opensource.org/faq#public-domain).
I suggest that you:
- See what it means when a software has [no license](https://choosealicense.com/no-permission/);
- Consider choosing a license from [choosealicense.com](https://choosealicense.com/).

**Comment by nikhilbansal97** [comment]
@rosariopfernandes I'll read about it. Thanks! 😄
